CREATE schema airbnb;

SET SEARCH_PATH TO airbnb;

CREATE TABLE USUARIO (
    UsrID INT NOT NULL,
    UsrNome VARCHAR(150) NOT NULL,
    UsrCPF VARCHAR(14) NOT NULL UNIQUE,
    UsrDtNasc DATE NOT NULL,
    PRIMARY KEY (UsrID)
);

CREATE TABLE CEP (
    CepID VARCHAR(10) NOT NULL ,
    CepRua VARCHAR(150) NOT NULL,
    CepBairro VARCHAR(100) NOT NULL,
    CepCidade VARCHAR(100) NOT NULL,
    CepEstado VARCHAR(2) NOT NULL,
    PRIMARY KEY (CepID)
);

CREATE TABLE TIPOAV (
    TipoAvID INT NOT NULL,
    TipoAVStr VARCHAR(50) NOT NULL,
    PRIMARY KEY (TipoAvID)
);

CREATE TABLE COMODIDADE (
    ComID INT NOT NULL,
    ComNome VARCHAR(100) NOT NULL,
    PRIMARY KEY (ComID)
);

-- TABELAS DE PRIMEIRO NÍVEL DE DEPENDÊNCIA

CREATE TABLE ANFITRIAO (
    UsrID INT NOT NULL,
    AnfDataInicio DATE NOT NULL,
    PRIMARY KEY (UsrID),
    FOREIGN KEY (UsrID) REFERENCES USUARIO(UsrID) ON DELETE CASCADE
);

CREATE TABLE HOSPEDE (
    UsrID INT NOT NULL,
    HosDataInicio DATE NOT NULL,
    PRIMARY KEY (UsrID),
    FOREIGN KEY (UsrID) REFERENCES USUARIO(UsrID) ON DELETE CASCADE
);

CREATE TABLE TELEFONE (
    TlfID INT NOT NULL ,
    TlfNumero VARCHAR(20) NOT NULL,
    UsrID INT NOT NULL,
    PRIMARY KEY (TlfID),
    FOREIGN KEY (UsrID) REFERENCES USUARIO(UsrID) ON DELETE CASCADE
);

CREATE TABLE ENDERECO (
    EndID INT NOT NULL ,
    EndNumero INT NOT NULL,
    EndComplemento VARCHAR(100),
    CepID VARCHAR(10) NOT NULL,
    PRIMARY KEY (EndID),
    FOREIGN KEY (CepID) REFERENCES CEP(CepID)
);

-- TABELAS DE SEGUNDO NÍVEL DE DEPENDÊNCIA

CREATE TABLE ANUNCIO (
    AnID INT NOT NULL ,
    AnTitulo VARCHAR(150) NOT NULL,
    AnDesc TEXT,
    AnCustoDiaUtil DECIMAL(10, 2) NOT NULL,
    AnCustoFimSem DECIMAL(10, 2) NOT NULL,
    AnfUsrID INT NOT NULL,
    PRIMARY KEY (AnID),
    FOREIGN KEY (AnfUsrID) REFERENCES ANFITRIAO(UsrID)
);

-- TABELAS DE TERCEIRO NÍVEL DE DEPENDÊNCIA E RELACIONAMENTOS N:M

CREATE TABLE ACOMODACAO (
    AcID INT NOT NULL ,
    AcCapacPessoa INT NOT NULL,
    AcQtdQuartos INT NOT NULL,
    AcQtdBanheiros INT NOT NULL,
    AnID INT NOT NULL UNIQUE,
    EndID INT NOT NULL UNIQUE,
    PRIMARY KEY (AcID),
    FOREIGN KEY (AnID) REFERENCES ANUNCIO(AnID) ON DELETE CASCADE,
    FOREIGN KEY (EndID) REFERENCES ENDERECO(EndID)
);

CREATE TABLE ACPOSSUICOM (
    AcID INT NOT NULL,
    ComID INT NOT NULL,
    PRIMARY KEY (AcID, ComID),
    FOREIGN KEY (AcID) REFERENCES ACOMODACAO(AcID) ON DELETE CASCADE,
    FOREIGN KEY (ComID) REFERENCES COMODIDADE(ComID) ON DELETE CASCADE
);

CREATE TABLE RESERVA (
    ResID INT NOT NULL ,
    ResDtIn DATE NOT NULL,
    ResDtOut DATE NOT NULL,
    ResStatus VARCHAR(50) NOT NULL,
    ResFormaPaga VARCHAR(50) NOT NULL,
    ResDataPaga DATE,
    ResQtdAdultos INT NOT NULL,
    ResQtdCriancas INT,
    ResQtdBebes INT,
    ResQtdPets INT,
    HosUsrID INT NOT NULL,
    AnID INT NOT NULL,
    PRIMARY KEY (ResID),
    FOREIGN KEY (HosUsrID) REFERENCES HOSPEDE(UsrID),
    FOREIGN KEY (AnID) REFERENCES ANUNCIO(AnID)
);

CREATE TABLE AVALIACAO (
    AvID INT NOT NULL ,
    AvNota INT NOT NULL,
    AvComentario TEXT,
    AvData DATE NOT NULL,
    AnID INT NOT NULL,
    AnfUsrID INT NOT NULL,
    HosUsrID INT NOT NULL,
    TipoAvID INT NOT NULL,
    ResID INT NOT NULL,
    PRIMARY KEY (AvID),
    FOREIGN KEY (AnID) REFERENCES ANUNCIO(AnID) ON DELETE CASCADE,
    FOREIGN KEY (AnfUsrID) REFERENCES ANFITRIAO(UsrID),
    FOREIGN KEY (HosUsrID) REFERENCES HOSPEDE(UsrID),
    FOREIGN KEY (TipoAvID) REFERENCES TIPOAV(TipoAvID),
    FOREIGN KEY (ResID) REFERENCES RESERVA(ResID)
);